dist: trusty
sudo: false
language: ruby

services:
  - mysql

rvm:
  - "2.5"
  - "2.4"
  - "2.3"

env:
  global:
    - RNP_VERSION="master"

    - DATABASE_URL="mysql2://travis@127.0.0.1/keyserver_test"

    - DEPS_BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
    - DEPS_PREFIX="${TRAVIS_BUILD_DIR}/opt"
    - BOTAN_PREFIX="${DEPS_PREFIX}/botan"
    - JSONC_PREFIX="${DEPS_PREFIX}/json-c"
    - RNP_PREFIX="${DEPS_PREFIX}/rnp"

    # Be aware of differences between LD_LIBRARY_PATH and LD_RUN_PATH.
    # - http://osr507doc.sco.com/en/tools/ccs_linkedit_dynamic_dirsearch.html
    # - https://www.hpc.dtu.dk/?page_id=1180
    #
    # You should be careful when attempting to replicate following in your
    # setup, because setting LD_LIBRARY_PATH is often a bad idea.  Nevertheless,
    # it is okay here in Travis, and actually any attempt to change these led me
    # to linking failures.  Side note: I am not a Linux expert, and you may be
    # more lucky.
    #
    # I'd be happy to get rid of LD_LIBRARY_PATH eventually in some future
    # pull request.
    - LD_LIBRARY_PATH="${BOTAN_PREFIX}/lib:${JSONC_PREFIX}/lib:${RNP_PREFIX}/lib"

    - PATH="${RNP_PREFIX}/bin:${PATH}"

cache:
  bundler: true
  directories:
    - "${DEPS_PREFIX}"

before_install:
  - gem install bundler -v 1.16.6
  - mysql -e 'CREATE DATABASE keyserver_test;'
  - mkdir -p ${DEPS_PREFIX}
  - pushd ci
  - ./install_botan.sh
  - ./install_json_c.sh
  - ./install_rnp.sh
  - popd

matrix:
  include:
    - rvm: "2.5"
      env: RNP_VERSION="v0.9.1"
    - rvm: "2.5"
      env: RNP_VERSION="v0.9.2"
    - rvm: "2.5"
      env: RNP_VERSION="v0.10.0"
    - rvm: "2.5"
      env: RNP_VERSION="v0.11.0"
