= Rails::Keyserver

image:https://img.shields.io/gem/v/rails-keyserver.svg[
	Gem Version, link="https://rubygems.org/gems/rails-keyserver"]
image:https://img.shields.io/travis/riboseinc/rails-keyserver/master.svg[
	Build Status, link="https://travis-ci.org/riboseinc/rails-keyserver/branches"]
image:https://img.shields.io/codecov/c/github/riboseinc/rails-keyserver.svg[
	Test Coverage, link="https://codecov.io/gh/riboseinc/rails-keyserver"]
image:https://img.shields.io/codeclimate/maintainability/riboseinc/rails-keyserver.svg[
	"Code Climate", link="https://codeclimate.com/github/riboseinc/rails-keyserver"]

Short description and motivation.

== Usage

How to use my plugin.

== Installation

Add this line to your application’s Gemfile:

[source,ruby]
----
gem 'rails-keyserver'
----

And then execute:

[source,console]
----
$ bundle
----

Or install it yourself as:

[source,console]
----
$ gem install rails-keyserver
----

== Contributing

First, thank you for contributing! We love pull requests from everyone.
By participating in this project, you hereby grant
https://www.ribose.com[Ribose Inc.] the right to grant or transfer an
unlimited number of non exclusive licenses or sub-licenses to third
parties, under the copyright covering the contribution to use the
contribution by all means.

Here are a few technical guidelines to follow:

1.  Open an https://github.com/riboseinc/rails-keyserver/issues[issue] to discuss
    a new feature.
2.  Write tests to support your new feature.
3.  Make sure the entire test suite passes locally and on CI.
4.  Open a Pull Request.
5.  After receiving feedback, perform
    https://help.github.com/articles/about-git-rebase/[an interactive rebase]
    on your branch, in order to create a series of cohesive commits with
    descriptive messages.
6.  Party!

== Credits

This gem is developed, maintained and funded by
https://www.ribose.com[Ribose Inc.]

== License

The gem is available as open source under the terms of the
http://opensource.org/licenses/MIT[MIT License].
